version: 0.2
phases:
  build:
    commands:
      - dotnet restore
      - dotnet build -c release
      - dotnet publish -c release -o ./asptest/wwwroot/buildoutput ./asptest/wwwroot/asptest.csproj
artifacts:
  files:
    - ./asptest/wwwroot/buildoutput/*
    - ./appspec.yml
  





